[package]
name = "velocity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="velocity"
path="./src/main.rs"

[dependencies]
serde_json = "1.0.91"
clap = { version="4.0.32", features=["derive"] }
